version: "3"

services:
  db:
    image: mariadb:10.3
    environment:
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .boing/docker/php
      args:
        INTL_REQUIRE: 1
    volumes:
      - .:/srv

  web:
    depends_on:
      - php
    build:
      context: .boing/docker/nginx/symfony
    volumes:
      - ./public:/srv/public
    ports:
      - "8000:80"

volumes:
  db_data:
